# Generated by Django 5.0.7 on 2024-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='noname', max_length=255)),
                ('description', models.TextField(default=None, max_length=2048)),
                ('price', models.BigIntegerField(default=0)),
                ('orders', models.BigIntegerField(default=0)),
            ],
        ),
    ]
